//! Chat endpoints. POST streams SSE: `tool` events, `delta` events, then
//! `done` (or `error`). Persistence is all-or-nothing after the stream
//! completes; replies are generated by the agent sidecar (`src/agent`).

use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::response::{IntoResponse, Response};
use axum::Json;
use futures_util::StreamExt;
use serde_json::json;

use super::AppState;
use crate::chat::store;
use crate::db;

#[derive(serde::Deserialize)]
pub struct ChatRequest {
    pub model_id: String,
    pub message: String,
}

fn sse_event(name: &str, data: serde_json::Value) -> Result<Event, std::convert::Infallible> {
    Ok(Event::default().event(name).data(data.to_string()))
}

pub async fn models(State(app): State<AppState>) -> Response {
    match &app.agent {
        None => Json(json!({ "available": false, "models": [] })).into_response(),
        Some(a) => {
            let models: Vec<_> = a
                .backends
                .iter()
                .map(|b| json!({ "id": b.id, "label": b.label }))
                .collect();
            Json(json!({ "available": true, "models": models })).into_response()
        }
    }
}

/// Look up a live (non-deleted) paper or answer 404/500. Mirrors the guard
/// pattern of the other paper endpoints in api.rs.
async fn live_paper(app: &AppState, id: &str) -> Result<crate::models::Paper, Response> {
    match db::get_by_id(&app.pool, id).await {
        Ok(Some(p)) if p.deleted_at.is_none() => Ok(p),
        Ok(_) => Err(StatusCode::NOT_FOUND.into_response()),
        Err(e) => {
            tracing::error!("chat paper lookup: {e}");
            Err(StatusCode::INTERNAL_SERVER_ERROR.into_response())
        }
    }
}

pub async fn history(State(app): State<AppState>, Path(id): Path<String>) -> Response {
    let paper = match live_paper(&app, &id).await {
        Ok(p) => p,
        Err(r) => return r,
    };
    match store::list(&app.pool, &paper.id).await {
        Ok(rows) => Json(rows).into_response(),
        Err(e) => {
            tracing::error!("chat history: {e}");
            StatusCode::INTERNAL_SERVER_ERROR.into_response()
        }
    }
}

pub async fn clear(State(app): State<AppState>, Path(id): Path<String>) -> Response {
    let paper = match live_paper(&app, &id).await {
        Ok(p) => p,
        Err(r) => return r,
    };
    match store::clear(&app.pool, &paper.id).await {
        Ok(()) => StatusCode::NO_CONTENT.into_response(),
        Err(e) => {
            tracing::error!("chat clear: {e}");
            StatusCode::INTERNAL_SERVER_ERROR.into_response()
        }
    }
}

pub async fn send(
    State(app): State<AppState>,
    Path(id): Path<String>,
    Json(req): Json<ChatRequest>,
) -> Response {
    use crate::agent::{AgentEvent, TurnMessage, TurnPaper, TurnRequest};

    let Some(agent) = app.agent.clone() else {
        return (
            StatusCode::SERVICE_UNAVAILABLE,
            Json(json!({"error": {"code": 503, "message": "agent ask is not configured"}})),
        )
            .into_response();
    };
    let paper = match live_paper(&app, &id).await {
        Ok(p) => p,
        Err(r) => return r,
    };
    let Some(backend) = agent.backend(&req.model_id).cloned() else {
        return (StatusCode::BAD_REQUEST, "unknown model_id").into_response();
    };
    let user_msg = req.message.trim().to_string();
    if user_msg.is_empty() {
        return (StatusCode::BAD_REQUEST, "empty message").into_response();
    }
    let history = match store::list(&app.pool, &paper.id).await {
        Ok(rows) => rows,
        Err(e) => {
            tracing::error!("chat history for send: {e}");
            return StatusCode::INTERNAL_SERVER_ERROR.into_response();
        }
    };
    let ws = match agent.ensure_workspace(&app.library_root, &paper).await {
        Ok(w) => w,
        Err(e) => {
            tracing::error!("agent workspace: {e}");
            return StatusCode::INTERNAL_SERVER_ERROR.into_response();
        }
    };
    let has_repo = tokio::fs::try_exists(ws.join("repo"))
        .await
        .unwrap_or(false);
    let treq = TurnRequest {
        backend: backend.id.clone(),
        model: backend.model.clone(),
        workspace: ws.to_string_lossy().into_owned(),
        has_repo,
        paper: TurnPaper::from_paper(&paper),
        transcript: history
            .iter()
            .map(|r| TurnMessage {
                role: r.role.clone(),
                content: r.content.clone(),
            })
            .collect(),
        question: user_msg.clone(),
    };
    let (pool, paper_id, label) = (app.pool.clone(), paper.id.clone(), backend.label.clone());

    let stream = async_stream::stream! {
        let upstream = agent.run_turn(treq);
        futures_util::pin_mut!(upstream);
        let mut full = String::new();
        let mut tools: Vec<serde_json::Value> = Vec::new();
        while let Some(ev) = upstream.next().await {
            match ev {
                AgentEvent::Delta { text } => {
                    full.push_str(&text);
                    yield sse_event("delta", json!({ "text": text }));
                }
                AgentEvent::Tool { name, detail } => {
                    tools.push(json!({ "name": name, "detail": detail }));
                    yield sse_event("tool", json!({ "name": name, "detail": detail }));
                }
                AgentEvent::Error { message } => {
                    yield sse_event("error", json!({ "message": message }));
                    return;
                }
                AgentEvent::Done => break,
            }
        }
        if full.is_empty() {
            yield sse_event("error", json!({ "message": "the agent returned an empty reply" }));
            return;
        }
        let tools_json = if tools.is_empty() {
            None
        } else {
            serde_json::to_string(&tools).ok()
        };
        // Client disconnects drop this stream before we get here, so
        // nothing is persisted for aborted generations.
        match store::insert_exchange(&pool, &paper_id, &user_msg, &full, &label, tools_json.as_deref()).await {
            Ok(assistant_id) => yield sse_event("done", json!({ "id": assistant_id })),
            Err(e) => yield sse_event("error", json!({ "message": format!("saving the exchange failed: {e}") })),
        }
    };
    Sse::new(stream)
        .keep_alive(KeepAlive::default())
        .into_response()
}
