//! Chat endpoints. POST streams SSE: `tool` events, `delta` events, then
//! `done` (or `error`). Persistence is all-or-nothing after the stream
//! completes; replies are generated by the agent sidecar (`src/agent`).

use anyhow::Context as _;
use axum::extract::{Path, State};
use axum::http::StatusCode;
use axum::response::sse::{Event, KeepAlive, Sse};
use axum::response::{IntoResponse, Response};
use axum::Json;
use futures_util::StreamExt;
use serde_json::json;

use super::api::{fetch_paper, Trash};
use super::dto::{ChatModel, ChatModels, ChatTurn};
use super::error::ApiError;
use super::AppState;
use crate::chat::store;

#[derive(serde::Deserialize)]
pub struct ChatRequest {
    pub model_id: String,
    pub message: String,
}

fn sse_event(name: &str, data: serde_json::Value) -> Result<Event, std::convert::Infallible> {
    Ok(Event::default().event(name).data(data.to_string()))
}

pub async fn models(State(app): State<AppState>) -> Json<ChatModels> {
    match &app.agent {
        None => Json(ChatModels {
            available: false,
            models: Vec::new(),
        }),
        Some(a) => Json(ChatModels {
            available: true,
            models: a
                .backends
                .iter()
                .map(|b| ChatModel {
                    id: b.id.clone(),
                    label: b.label.clone(),
                })
                .collect(),
        }),
    }
}

pub async fn history(
    State(app): State<AppState>,
    Path(id): Path<String>,
) -> Result<Response, ApiError> {
    let paper = fetch_paper(&app.pool, &id, Trash::Deny, "chat").await?;
    let rows = store::list(&app.pool, &paper.id)
        .await
        .context("chat history")?;
    let turns: Vec<ChatTurn> = rows.into_iter().map(ChatTurn::from).collect();
    Ok(Json(turns).into_response())
}

pub async fn clear(
    State(app): State<AppState>,
    Path(id): Path<String>,
) -> Result<Response, ApiError> {
    let paper = fetch_paper(&app.pool, &id, Trash::Deny, "chat").await?;
    store::clear(&app.pool, &paper.id)
        .await
        .context("chat clear")?;
    Ok(StatusCode::NO_CONTENT.into_response())
}

pub async fn send(
    State(app): State<AppState>,
    Path(id): Path<String>,
    Json(req): Json<ChatRequest>,
) -> Result<Response, ApiError> {
    use crate::agent::{AgentEvent, TurnMessage, TurnPaper, TurnRequest};

    let Some(agent) = app.agent.clone() else {
        return Err(ApiError::Unavailable("agent ask is not configured"));
    };
    let paper = fetch_paper(&app.pool, &id, Trash::Deny, "chat").await?;
    let Some(backend) = agent.backend(&req.model_id).cloned() else {
        return Err(ApiError::BadRequest("unknown model_id".into()));
    };
    let user_msg = req.message.trim().to_string();
    if user_msg.is_empty() {
        return Err(ApiError::BadRequest("empty message".into()));
    }
    let history = store::list(&app.pool, &paper.id)
        .await
        .context("chat history for send")?;
    let ws = agent
        .ensure_workspace(&app.library_root, &paper)
        .await
        .context("agent workspace")?;
    // Gate on the DB record, not just disk: a detach clears the row, but a
    // clone job racing that detach can leave a stray `repo/` behind. Trusting
    // disk alone would expose that orphaned checkout; requiring status = 'ready'
    // (and that the directory is actually present) does not.
    let repo_ready = matches!(
        crate::agent::store::get_paper_code(&app.pool, &paper.id).await,
        Ok(Some(c)) if c.status == crate::agent::store::CodeStatus::Ready
    );
    let has_repo = repo_ready
        && tokio::fs::try_exists(ws.join("repo"))
            .await
            .unwrap_or(false);
    let treq = TurnRequest {
        backend: backend.id.clone(),
        model: backend.model.clone(),
        workspace: ws.to_string_lossy().into_owned(),
        has_repo,
        paper: TurnPaper::from_paper(&paper),
        transcript: history
            .iter()
            .map(|r| TurnMessage {
                role: r.role.clone(),
                content: r.content.clone(),
            })
            .collect(),
        question: user_msg.clone(),
    };
    let (pool, paper_id, label) = (app.pool.clone(), paper.id.clone(), backend.label.clone());

    let stream = async_stream::stream! {
        let upstream = agent.run_turn(treq);
        futures_util::pin_mut!(upstream);
        let mut full = String::new();
        let mut tools: Vec<serde_json::Value> = Vec::new();
        while let Some(ev) = upstream.next().await {
            match ev {
                AgentEvent::Delta { text } => {
                    full.push_str(&text);
                    yield sse_event("delta", json!({ "text": text }));
                }
                AgentEvent::Tool { name, detail } => {
                    tools.push(json!({ "name": name, "detail": detail }));
                    yield sse_event("tool", json!({ "name": name, "detail": detail }));
                }
                AgentEvent::Error { message } => {
                    yield sse_event("error", json!({ "message": message }));
                    return;
                }
                AgentEvent::Done => break,
            }
        }
        if full.is_empty() {
            yield sse_event("error", json!({ "message": "the agent returned an empty reply" }));
            return;
        }
        let tools_json = if tools.is_empty() {
            None
        } else {
            serde_json::to_string(&tools).ok()
        };
        // Client disconnects drop this stream before we get here, so
        // nothing is persisted for aborted generations.
        match store::insert_exchange(&pool, &paper_id, &user_msg, &full, &label, tools_json.as_deref()).await {
            Ok(assistant_id) => yield sse_event("done", json!({ "id": assistant_id })),
            Err(e) => yield sse_event("error", json!({ "message": format!("saving the exchange failed: {e}") })),
        }
    };
    Ok(Sse::new(stream)
        .keep_alive(KeepAlive::default())
        .into_response())
}
